version: '3'
services:
    bitcore-node-sync:
        container_name: bitcore-node-sync
        image: bitcorestrax.azurecr.io/bitcore-node
        ports:
        - 4000:3000
        volumes:
        - /root/config:/config
        environment:
            - BITCORE_CONFIG_PATH=/config/bitcore.config.prod.json
        restart: always