apiVersion: 2019-12-01
location: uksouth
name: cirrus-node
properties:
  containers:
  - name: mongo
    properties:
      image: mongo
      resources:
        requests:
          cpu: 0.5
          memoryInGb: 1
      volumeMounts:
      - name: bitcorestratisdb
        mountPath: /data/db
        readOnly: false
  osType: Linux
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 16179
  volumes:
  - name: bitcorestratisdb
    azureFile:
      shareName: cirrus
      readOnly: false
      storageAccountName: bitcorestratis
      storageAccountKey: OG8QpckNOZLKeQ7beWpC/qz2XMzUgXnw+46/vHetl5P+NUCFKDTv+x/57vkWZ2oAhsTEzgmgZTf+AeBWMGdJIg==
  imageRegistryCredentials: 
  - server: bitcorestrax.azurecr.io
    username: bitcorestrax
    password: s7txk1wVYd2/ECQ+zIpsK2LIO8c/k1dW
type: Microsoft.ContainerInstance/containerGroups