version: '3'
services:
    database:
        image: mongo
        container_name: mongodb-bitcore
        volumes:
          - fileshare:/data/db
        command: mongod
        restart: always
        deploy:
            resources:
                limits:
                    memory: 2g
                    cpus: '1.4'
    
    bitcore-node:
        build:
            context: ../
            dockerfile: Docker/Dockerfile
        container_name: bitcore-node
        image: bitcorestrax.azurecr.io/bitcore-node
        depends_on:
        - database
        ports:
        - 3000:3000        
        environment:
            - DB_HOST=localhost
            - DB_PORT=27017
            - BITCORE_CONFIG_PATH=/config/bitcore.config.json
        volumes:
          - config:/config
        restart: always
        deploy:
            resources:
                limits:
                    memory: 3g
                    cpus: '2'        

    bitcore-wallet-service:
        build:
            context: ../
            dockerfile: Docker/bws.Dockerfile
        container_name: bitcore-wallet-service
        image: bitcorestrax.azurecr.io/bws
        depends_on:
        - database
        - bitcore-node
        ports:
        - 3032:3032
        environment:
            - DB_HOST=localhost
            - DB_PORT=27017
            - BWS_CONFIG_PATH=/config/bws.config.js
        volumes:
          - config:/config
        restart: always
        deploy:
            resources:
                limits:
                    memory: 1g
                    cpus: '0.5'        

volumes:
    fileshare:
        driver: azure_file
        driver_opts:
            share_name: bitcorestratisdb
            storage_account_name: bitcorestratis
    config:
        driver: azure_file
        driver_opts:
            share_name: configs
            storage_account_name: bitcorestratis